### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by bixiaopeng0** [leolyliu/SuperGlue_SuperPoint_MegaDepth#1]
请问您在megadepth上有评测过精度吗，以及可视化的匹配效果。

**Comment by leolyliu** [comment]
有自定义评测指标，有可视化匹配效果。

**Comment by leolyliu** [comment]
> 请问您在megadepth上有评测过精度吗，以及可视化的匹配效果。

有自定义评测指标，有可视化匹配效果。
