### ISSUE TITLE
How to train on coco dataset

### ISSUE THREAD

**Issue by ChrisLLLLL** [leolyliu/SuperGlue_SuperPoint_MegaDepth#2]
I found that it seems that it can only be trained on the megadepth dataset? looking forward to your reply,thank you

**Comment by leolyliu** [comment]
> I found that it seems that it can only be trained on the megadepth dataset? looking forward to your reply,thank you

It can only be trained on the MegaDepth dataset. You can define the COCODataset class similar to the MegaDepthDataset class to train on the COCO dataset, and change the source of images and functions of searching matches.
